### ISSUE TITLE
Release description no longer lists images

### ISSUE THREAD

**Issue by steakunderscore** [VJftw/cloud-desktops#8]
It use to be that the release description contained the release images. For example [2022-06-17-3834e7a](https://github.com/VJftw/cloud-desktops/releases/tag/2022-06-17-3834e7a) with:
```
kali-xfce4-2022-06-17-3834e7a
debian-xfce4-2022-06-17-3834e7a
```

However as of [2022-07-01-3e5a379](https://github.com/VJftw/cloud-desktops/releases/tag/2022-07-01-3e5a379) the release description is blank.

**Comment by steakunderscore** [comment]
This might be related[1]
```
Warning: No files were found with the provided path: plz-out/**/packer-manifest.json. No artifacts will be uploaded.
```
[1]: https://github.com/VJftw/cloud-desktops/runs/7244487920?check_suite_focus=true

**Comment by steakunderscore** [comment]
Looks like you're no longer using the default[1] of `packer-manifest.json`, but overriding this with[2]:

```hcl2
post-processor "manifest" {                                                                                                                                                                                
       output = "manifest.json"                                                  
       strip_path = true                                                         
}
```

[1]: https://www.packer.io/docs/post-processors/manifest#output
[2]: https://github.com/VJftw/cloud-desktops/blob/main/flavours/debian/xfce4.pkr.hcl#L55

**Comment by VJftw** [comment]
Can confirm that #9 fixed it! Thanks again! ❤️ 
(https://github.com/VJftw/cloud-desktops/releases/tag/2022-08-04-3a9548b)
